name: Rust CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Запускать публикацию релиза только при публикации нового релиза в GitHub
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Джоба 1: Проверка кода (запускается на каждый пуш и PR)
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check code
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose

  # Джоба 2: Сборка релиза (запускается только при публикации релиза)
  release:
    if: github.event_name == 'release'
    needs: check # Сначала проверяем код
    runs-on: windows-latest # Собираем под Windows

    steps:
    - uses: actions/checkout@v4

    - name: Build Release
      run: cargo build --release --verbose

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/glscript-language-server.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
